#!/bin/bash

read -p "Enter a string: " str

# Reverse the string
rev_str=$(echo "$str" | rev)

if [ "$str" == "$rev_str" ]; then
    echo "$str is a palindrome"
else
    echo "$str is not a palindrome"
fi
